version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  backend:
    image: recipes-suggester
    build:
      context: .
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    command: gunicorn main:create_app --worker-class aiohttp.GunicornWebWorker --bind 0.0.0.0:80 --access-logfile - --error-logfile - --log-level debug
    expose:
      - 9200
    ports:
      - 80:80
